trigger:
- main

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        addToPath: true
      
    - script: |
        docker build -t myflaskapp:$(Build.BuildId) .
      displayName: 'Build Docker Image'
      
    - script: |
        docker run --rm -v $(System.DefaultWorkingDirectory)/testresults:/app/testresults myflaskapp:$(Build.BuildId) pytest --junitxml=/app/testresults/test-results.xml
      displayName: 'Run Tests in Docker Container'
      continueOnError: true

    - publish: $(Pipeline.Workspace)/testresults
      artifact: testresults

- stage: Test
  dependsOn: Build
  jobs:
  - job: TestJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: testresults

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-results.xml'
        failTaskOnFailedTests: true
        testRunTitle: 'Flask App Tests'
