trigger:
- main

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'myflaskapp:$(Build.BuildId)'
        buildContext: '.'
        arguments: '--build-arg FLASK_ENV=$(FLASK_ENV) --build-arg FLASK_SECRET_KEY=$(FLASK_SECRET_KEY)'

    - script: |
        docker run --rm myflaskapp:$(Build.BuildId) python -m pytest tests/ --cov trippy --cov-report html
      displayName: 'Run Tests in Docker Container'
      continueOnError: true
      
    - script: |
        docker run --rm myflaskapp:$(Build.BuildId) flake8
      displayName: 'Flake8'
      continueOnError: true
