# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
        arguments: 'FLASK_ENV="$(FLASK_ENV)" FLASK_SECRET_KEY="$(FLASK_SECRET_KEY)" WTF_CSRF_SECRET_KEY="$(WTF_CSRF_SECRET_KEY)" AZURE_STORAGE_CONTAINER_NAME="$(AZURE_STORAGE_CONTAINER_NAME)" AZURE_STORAGE_CONNECTION_STRING="$(AZURE_STORAGE_CONNECTION_STRING)"'

- stage: Lint
  jobs:
    - job: Flake8
      displayName: Lint with Flake8
      steps:
        - script: flake8
- stage: Test
  jobs:
    - job: Tests
      displayName: Run tests and coverage
      steps:
        - script: |
            coverage run -m pytest
            coverage report

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: '.coverage'
            testRunTitle: '$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)]'
          condition: succeededOrFailed()

