trigger:
- master

variables:
  imageName: ubuntu-latest

jobs:
- job: 'Test'
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
      architecture: 'x64'

  - script: python -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m flake8
    displayName: 'Run lint tests'
    continueOnError: true 

  - script: |
      python -m pytest
    displayName: 'Run pytest tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'