trigger:
- main

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
 
    - script: |
        docker build -t myflaskapp:$(Build.BuildId) --build-arg FLASK_ENV=$(FLASK_ENV) --build-arg FLASK_SECRET_KEY=$(FLASK_SECRET_KEY) .
      displayName: 'Build Docker Image'
      
    - script: |
        docker run --rm myflaskapp:$(Build.BuildId) python -m pytest tests/ --cov trippy --cov-report html
      displayName: 'Run Tests in Docker Container'
      continueOnError: true
      
    - script: |
        docker run --rm myflaskapp:$(Build.BuildId) flake8
      displayName: 'Flake8'
      continueOnError: true


